#!/usr/bin/env python3
"""
Version information for the DeepSeek Desktop application.
This file is automatically generated during the build process.
"""

# Version string
__version__ = "0.1.61"

# For backward compatibility
VERSION = __version__
